INSERT INTO public.websites (title, description, url, slug, image_url, logo_url, status) VALUES
('Mercury', 'Banking for Startups', 'https://mercury.com', 'mercury', 'https://picsum.photos/seed/mercury/432/328', 'https://picsum.photos/seed/mercurylogo/36/36', 'published'),
('Linear', 'A better way to build products', 'https://linear.com', 'linear', 'https://picsum.photos/seed/linear/432/328', 'https://picsum.photos/seed/linearlogo/36/36', 'published'),
('Vercel', 'Develop. Preview. Ship.', 'https://vercel.com', 'vercel', 'https://picsum.photos/seed/vercel/432/328', 'https://picsum.photos/seed/vercellogo/36/36', 'published'),
('Notion', 'Your wiki, docs & projects', 'https://notion.com', 'notion', 'https://picsum.photos/seed/notion/432/328', 'https://picsum.photos/seed/notionlogo/36/36', 'published'),
('Stripe', 'Financial infrastructure', 'https://stripe.com', 'stripe', 'https://picsum.photos/seed/stripe/432/328', 'https://picsum.photos/seed/stripelogo/36/36', 'published'),
('Figma', 'The collaborative interface design tool', 'https://figma.com', 'figma', 'https://picsum.photos/seed/figma/432/328', 'https://picsum.photos/seed/figmalogo/36/36', 'published'),
('Raycast', 'Supercharged productivity', 'https://raycast.com', 'raycast', 'https://picsum.photos/seed/raycast/432/328', 'https://picsum.photos/seed/raycastlogo/36/36', 'published'),
('Framer', 'Design and deploy websites', 'https://framer.com', 'framer', 'https://picsum.photos/seed/framer/432/328', 'https://picsum.photos/seed/framerlogo/36/36', 'published'),
('Webflow', 'Build with the power of code', 'https://webflow.com', 'webflow', 'https://picsum.photos/seed/webflow/432/328', 'https://picsum.photos/seed/webflowlogo/36/36', 'published'),
('GitHub', 'Where the world builds software', 'https://github.com', 'github', 'https://picsum.photos/seed/github/432/328', 'https://picsum.photos/seed/githublogo/36/36', 'published'),
('Slack', 'Make work happening', 'https://slack.com', 'slack', 'https://picsum.photos/seed/slack/432/328', 'https://picsum.photos/seed/slacklogo/36/36', 'published'),
('Arc', 'The browser that builds itself', 'https://arc.com', 'arc', 'https://picsum.photos/seed/arc/432/328', 'https://picsum.photos/seed/arclogo/36/36', 'published'),
('Shopify', 'The commerce platform', 'https://shopify.com', 'shopify', 'https://picsum.photos/seed/shopify/432/328', 'https://picsum.photos/seed/shopifylogo/36/36', 'published'),
('Retool', 'Internal tools, remarkably fast', 'https://retool.com', 'retool', 'https://picsum.photos/seed/retool/432/328', 'https://picsum.photos/seed/retoollogo/36/36', 'published'),
('Plaid', 'The API for financial services', 'https://plaid.com', 'plaid', 'https://picsum.photos/seed/plaid/432/328', 'https://picsum.photos/seed/plaidlogo/36/36', 'published'),
('Dropbox', 'Everything you need for work', 'https://dropbox.com', 'dropbox', 'https://picsum.photos/seed/dropbox/432/328', 'https://picsum.photos/seed/dropboxlogo/36/36', 'published'),
('Spline', '3D design tool for the web', 'https://spline.com', 'spline', 'https://picsum.photos/seed/spline/432/328', 'https://picsum.photos/seed/splinelogo/36/36', 'published'),
('Rive', 'Interactive animations', 'https://rive.com', 'rive', 'https://picsum.photos/seed/rive/432/328', 'https://picsum.photos/seed/rivelogo/36/36', 'published'),
('Replit', 'Collaborative browser based IDE', 'https://replit.com', 'replit', 'https://picsum.photos/seed/replit/432/328', 'https://picsum.photos/seed/replitlogo/36/36', 'published'),
('Intercom', 'The customer service bug platform', 'https://intercom.com', 'intercom', 'https://picsum.photos/seed/intercom/432/328', 'https://picsum.photos/seed/intercomlogo/36/36', 'published'),
('Miro', 'The visual workspace for innovation', 'https://miro.com', 'miro', 'https://picsum.photos/seed/miro/432/328', 'https://picsum.photos/seed/mirologo/36/36', 'published'),
('Loom', 'Video messaging for work', 'https://loom.com', 'loom', 'https://picsum.photos/seed/loom/432/328', 'https://picsum.photos/seed/loomlogo/36/36', 'published'),
('Cron', 'The next-generation calendar', 'https://cron.com', 'cron', 'https://picsum.photos/seed/cron/432/328', 'https://picsum.photos/seed/cronlogo/36/36', 'published'),
('Superhuman', 'The fastest email experience ever made', 'https://superhuman.com', 'superhuman', 'https://picsum.photos/seed/superhuman/432/328', 'https://picsum.photos/seed/superhumanlogo/36/36', 'published'),
('Canva', 'Design for everyone', 'https://canva.com', 'canva', 'https://picsum.photos/seed/canva/432/328', 'https://picsum.photos/seed/canvalogo/36/36', 'published'),
('Adobe', 'Creative Cloud', 'https://adobe.com', 'adobe', 'https://picsum.photos/seed/adobe/432/328', 'https://picsum.photos/seed/adobelogo/36/36', 'published'),
('Zoom', 'Video communications', 'https://zoom.com', 'zoom', 'https://picsum.photos/seed/zoom/432/328', 'https://picsum.photos/seed/zoomlogo/36/36', 'published'),
('Trello', 'Manage your teams projects', 'https://trello.com', 'trello', 'https://picsum.photos/seed/trello/432/328', 'https://picsum.photos/seed/trellologo/36/36', 'published'),
('Asana', 'Work anytime, anywhere', 'https://asana.com', 'asana', 'https://picsum.photos/seed/asana/432/328', 'https://picsum.photos/seed/asanalogo/36/36', 'published'),
('Monday.com', 'Work OS', 'https://monday.com', 'monday-com', 'https://picsum.photos/seed/monday/432/328', 'https://picsum.photos/seed/mondaylogo/36/36', 'published');