export const cardsData = [
  { id: 1, name: 'mercury', title: 'Mercury', subtitle: 'Banking for Startups', image: 'https://picsum.photos/seed/mercury/432/328', logo: 'https://picsum.photos/seed/mercurylogo/36/36', link: '#' },
  { id: 2, name: 'linear', title: 'Linear', subtitle: 'A better way to build products', image: 'https://picsum.photos/seed/linear/432/328', logo: 'https://picsum.photos/seed/linearlogo/36/36', link: '#' },
  { id: 3, name: 'vercel', title: 'Vercel', subtitle: 'Develop. Preview. Ship.', image: 'https://picsum.photos/seed/vercel/432/328', logo: 'https://picsum.photos/seed/vercellogo/36/36', link: '#' },
  { id: 4, name: 'notion', title: 'Notion', subtitle: 'Your wiki, docs & projects', image: 'https://picsum.photos/seed/notion/432/328', logo: 'https://picsum.photos/seed/notionlogo/36/36', link: '#' },
  { id: 5, name: 'stripe', title: 'Stripe', subtitle: 'Financial infrastructure', image: 'https://picsum.photos/seed/stripe/432/328', logo: 'https://picsum.photos/seed/stripelogo/36/36', link: '#' },
  { id: 6, name: 'figma', title: 'Figma', subtitle: 'The collaborative interface design tool', image: 'https://picsum.photos/seed/figma/432/328', logo: 'https://picsum.photos/seed/figmalogo/36/36', link: '#' },
  { id: 7, name: 'raycast', title: 'Raycast', subtitle: 'Supercharged productivity', image: 'https://picsum.photos/seed/raycast/432/328', logo: 'https://picsum.photos/seed/raycastlogo/36/36', link: '#' },
  { id: 8, name: 'framer', title: 'Framer', subtitle: 'Design and deploy websites', image: 'https://picsum.photos/seed/framer/432/328', logo: 'https://picsum.photos/seed/framerlogo/36/36', link: '#' },
  { id: 9, name: 'webflow', title: 'Webflow', subtitle: 'Build with the power of code', image: 'https://picsum.photos/seed/webflow/432/328', logo: 'https://picsum.photos/seed/webflowlogo/36/36', link: '#' },
  { id: 10, name: 'github', title: 'GitHub', subtitle: 'Where the world builds software', image: 'https://picsum.photos/seed/github/432/328', logo: 'https://picsum.photos/seed/githublogo/36/36', link: '#' },
  { id: 11, name: 'slack', title: 'Slack', subtitle: 'Make work happening', image: 'https://picsum.photos/seed/slack/432/328', logo: 'https://picsum.photos/seed/slacklogo/36/36', link: '#' },
  { id: 12, name: 'arc', title: 'Arc', subtitle: 'The browser that builds itself', image: 'https://picsum.photos/seed/arc/432/328', logo: 'https://picsum.photos/seed/arclogo/36/36', link: '#' },
  { id: 13, name: 'shopify', title: 'Shopify', subtitle: 'The commerce platform', image: 'https://picsum.photos/seed/shopify/432/328', logo: 'https://picsum.photos/seed/shopifylogo/36/36', link: '#' },
  { id: 14, name: 'retool', title: 'Retool', subtitle: 'Internal tools, remarkably fast', image: 'https://picsum.photos/seed/retool/432/328', logo: 'https://picsum.photos/seed/retoollogo/36/36', link: '#' },
  { id: 15, name: 'plaid', title: 'Plaid', subtitle: 'The API for financial services', image: 'https://picsum.photos/seed/plaid/432/328', logo: 'https://picsum.photos/seed/plaidlogo/36/36', link: '#' },
  { id: 16, name: 'dropbox', title: 'Dropbox', subtitle: 'Everything you need for work', image: 'https://picsum.photos/seed/dropbox/432/328', logo: 'https://picsum.photos/seed/dropboxlogo/36/36', link: '#' },
  { id: 17, name: 'spline', title: 'Spline', subtitle: '3D design tool for the web', image: 'https://picsum.photos/seed/spline/432/328', logo: 'https://picsum.photos/seed/splinelogo/36/36', link: '#' },
  { id: 18, name: 'rive', title: 'Rive', subtitle: 'Interactive animations', image: 'https://picsum.photos/seed/rive/432/328', logo: 'https://picsum.photos/seed/rivelogo/36/36', link: '#' },
  { id: 19, name: 'replit', title: 'Replit', subtitle: 'Collaborative browser based IDE', image: 'https://picsum.photos/seed/replit/432/328', logo: 'https://picsum.photos/seed/replitlogo/36/36', link: '#' },
  { id: 20, name: 'intercom', title: 'Intercom', subtitle: 'The customer service bug platform', image: 'https://picsum.photos/seed/intercom/432/328', logo: 'https://picsum.photos/seed/intercomlogo/36/36', link: '#' },
  { id: 21, name: 'miro', title: 'Miro', subtitle: 'The visual workspace for innovation', image: 'https://picsum.photos/seed/miro/432/328', logo: 'https://picsum.photos/seed/mirologo/36/36', link: '#' },
  { id: 22, name: 'loom', title: 'Loom', subtitle: 'Video messaging for work', image: 'https://picsum.photos/seed/loom/432/328', logo: 'https://picsum.photos/seed/loomlogo/36/36', link: '#' },
  { id: 23, name: 'cron', title: 'Cron', subtitle: 'The next-generation calendar', image: 'https://picsum.photos/seed/cron/432/328', logo: 'https://picsum.photos/seed/cronlogo/36/36', link: '#' },
  { id: 24, name: 'superhuman', title: 'Superhuman', subtitle: 'The fastest email experience ever made', image: 'https://picsum.photos/seed/superhuman/432/328', logo: 'https://picsum.photos/seed/superhumanlogo/36/36', link: '#' }
];
